### ISSUE TITLE
Add "one" function

### ISSUE THREAD

**Issue by mgaitan** [mahmoud/boltons#23]
I have a tiny package called `one` with just one "missing" function *" to check if there is a unique value that evaluates to True in an iterable"*. 

https://github.com/mgaitan/one

I propose to merge it in the boltons's  `iterutils` module. I can send a PR if you like it

**Comment by mahmoud** [comment]
Sure, I could definitely see the use there! A PR would be ideal because then you'd be forever immortalized in the `git blame` ;)

Docstring with a couple doctests demonstrating usage is all I ask. Don't forget to add `one` to the `__all__` of `iterutils` so it shows up in the docs. If you plan on continuing to maintain a separate package for one, maybe put a link in the docstring, too.

**Comment by mgaitan** [comment]
Merged in 4430b8669b
