### ISSUE TITLE
Thread pool

### ISSUE THREAD

**Issue by ssundarraj** [mahmoud/boltons#24]
So I have a small [thread pool library](http://github.com/srirams6/py-threadpool). I've noticed that the existing python thread pool implementations are not well maintained and/or have insufficient documentation. 

Would merging this with boltons be entertained?

Thanks,
Sriram

**Comment by ekimekim** [comment]
Now that you mention it, I have a "general" Pool implementation lying around. You give it a "create" and "destroy" function, as well as some mins and maxes, and it'll do all the reuse logic for an arbitrary resource. Maybe instead of having seperate ThreadPools, ConnPools, etc, we could have a `poolutils` that contains the general Pool as well as subclasses that implement the common cases like Thread and Conn. I'll make a seperate PR.

If that's not something we want to do, I'll also comment in general: I do think it's valuable to have a "better than stdlib" threadpool implementation, though you'd need to adapt your code slightly to be more self-contained (single file), as per the architecture guidelines.

**Comment by srirams6** [comment]
So if I adapted it to conform to the architecture guidelines, would a PR be entertained?

**Comment by mahmoud** [comment]
It's a good question. I haven't had a chance to review this in depth yet. Due to some preexisting plans this weekend is pretty busy for me, so I'll probably get to this by Tuesday or Wednesday. I will say that I have pretty high standards for anything involving syscalls of this nature. Furthermore, concurrency/parallelism can really shape an application's architecture in ways that most boltons wouldn't, so it's not something one can take lightly :)

**Comment by srirams6** [comment]
That sounds highly reasonable. Anyway, I've sent a PR (#27). Check it out. 
I think it would be a good feature if implemented well.
