### ISSUE TITLE
IndexedSet docs refer to (missing) UniqueList

### ISSUE THREAD

**Issue by xpe** [mahmoud/boltons#250]
From: https://boltons.readthedocs.io/en/latest/setutils.html#boltons.setutils.IndexedSet

> As you can see, the IndexedSet is almost like a UniqueList, retaining only one copy of a given value, in the order it was first added. 

This appears incorrect. Perhaps it is a remnant from an earlier version of the library?

**Comment by mahmoud** [comment]
Ah, that was more of a conceptual comparison. UniqueList was never part of the library, hence "a UniqueList" instead of "the UniqueList". 

Maybe if I tweaked the capitalization/spacing to look less like a type? But I think maybe my thought back then was to pick up some UniqueList SEO :P What do you think?
