### ISSUE TITLE
Python 3.12 warning: Use of naïve datetimes is deprecated

### ISSUE THREAD

**Issue by duncanmmacleod** [mahmoud/boltons#369]
Apologies if this has already been reported elsewhere, but importing `boltons.timeutils` (24.0.0) on Python 3.12 emits the following deprecation warning:

```pytb
/Users/duncan/opt/mambaforge/lib/python3.12/site-packages/boltons/timeutils.py:426: DeprecationWarning: datetime.datetime.utcfromtimestamp() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.fromtimestamp(timestamp, datetime.UTC).
  EPOCH_NAIVE = datetime.utcfromtimestamp(0)
```

I had a quick look at a patch, but don't really understand the implications of just 'removing' support for naïve datetimes in this module.

**Comment by mahmoud** [comment]
Hey Duncan! Yes, I've been seeing these warnings, too. This functionality exists as backwards compat for other code which might be using deprecated techniques, so you're right, it's not as simple as deleting the constant. Thankfully it's not part of the timeutils documented API, so I think we can still justifiably cut some code and get rid of the warning.

Because the only code that uses that constant is `dt_to_timestamp`, and the docs for that say that naive timestamps are assumed to be UTC, then we can convert the incoming naive datetime argument `dt` to a tz-aware datetime for the purposes of the calculation. This should have the same output. I'll cc you on the PR for a review. Thanks for the report and giving me a reason to tackle this sooner rather than later :)
