### ISSUE TITLE
consider combining efforts with unstdlib

### ISSUE THREAD

**Issue by ericfrederich** [mahmoud/boltons#89]
[unstdlib](https://github.com/shazow/unstdlib.py) seems to have similar goals as this project.

There are some things in there which I like to use such as [listify](https://github.com/shazow/unstdlib.py/blob/master/unstdlib/standard/list_.py)

I an always use both of these projects, but would be nice to combine efforts

**Comment by mahmoud** [comment]
Hey Eric, thanks for your interest! Always great to meet a boltons user. :) As for this issue, unstdlib is fine and well, but it's not super actively maintained, and clearly wasn't built with boltons' [architecture](http://boltons.readthedocs.io/en/latest/architecture.html) in mind. If there are specific functionalities you'd like to see, I'm happy to evaluate merging/duplicating them over (with proper attribution), but otherwise, two may be better than one :)

Thanks again!

**Comment by mblahay** [comment]
This issue should probably be closed due to age and the fact that it isn't going to be done. Just a suggestion to help clear up the issues list.

**Comment by mahmoud** [comment]
Fair :)
